.PHONY: build test lint clean format help openapi-generate openapi-check

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

build: ## Build all targets
	swift build

test: ## Run all tests
	swift test

lint: ## Lint with SwiftLint
	swiftlint lint --strict

format: ## Format with SwiftFormat (if available)
	swiftformat Sources/ Tests/ --swiftversion 5.9

clean: ## Clean build artifacts
	swift package clean
	rm -rf .build/

openapi-generate: ## Regenerate OpenAPI types + client from octomil-contracts
	OCTOMIL_IOS_PATH=$(PWD) OCTOMIL_IOS=1 \
	    ../octomil-contracts/tools/sdkgen/generate-swift.sh

openapi-check: ## Verify generated files carry correct AUTOGENERATED banner
	./scripts/check_openapi_banner.sh
