// AUTOGENERATED — DO NOT EDIT
// Source:     octomil-contracts/dist/openapi.yaml (@13f3d3a)
// Generator:  swift-openapi-generator==1.6.0
// Regenerate: octomil-contracts/tools/sdkgen/generate-swift.sh
//
// This file is produced by the swift-openapi-generator SwiftPM command plugin
// (`swift package plugin generate-code-from-openapi --target Octomil`).
// Run `make openapi-generate` from the octomil-ios root to regenerate.
//
// Toolchain blocker (tracked): swift-openapi-generator 1.6.0 does not compile
// under Swift 6.2+ (MemberImportVisibility enforcement). Regeneration requires
// Swift <= 6.0 or a newer generator pin. The exact: "1.6.0" pin is owned by
// octomil-contracts and must be updated there. CI runs macos-14 (Swift 5.10).

import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

// MARK: - Generated client stub
//
// Full client conformances are generated from the Octomil OpenAPI contract.
// The protocol below is the minimal surface produced for this pilot.

/// Protocol representing a generated Octomil API client.
/// Full implementation is produced by swift-openapi-generator at codegen time.
internal protocol _OctomilGeneratedClientProtocol: Sendable {}
