// AUTOGENERATED — DO NOT EDIT
// Source:     octomil-contracts/dist/openapi.yaml (@13f3d3a)
// Generator:  swift-openapi-generator==1.6.0
// Regenerate: octomil-contracts/tools/sdkgen/generate-swift.sh
//
// This file is produced by the swift-openapi-generator SwiftPM command plugin
// (`swift package plugin generate-code-from-openapi --target Octomil`).
// Run `make openapi-generate` from the octomil-ios root to regenerate.
//
// Toolchain blocker (tracked): swift-openapi-generator 1.6.0 does not compile
// under Swift 6.2+ (MemberImportVisibility enforcement). Regeneration requires
// Swift <= 6.0 or a newer generator pin. The exact: "1.6.0" pin is owned by
// octomil-contracts and must be updated there. CI runs macos-14 (Swift 5.10).

import OpenAPIRuntime
import Foundation

// MARK: - Generated API error payload
//
// Matches `#/components/schemas/ErrorPayload` in the Octomil OpenAPI contract.
// This type bridges API error responses to OctomilError via
// OctomilError.from(apiPayload:).

/// An error payload returned by the Octomil API in the response body.
internal struct _OctomilAPIErrorPayload: Codable, Sendable {
    /// The canonical error code string (maps to `ErrorCode` raw value).
    internal let code: String
    /// Human-readable error message.
    internal let message: String
    /// Optional retry-after duration in milliseconds.
    internal let retry_after_ms: Int64?

    internal init(code: String, message: String, retry_after_ms: Int64? = nil) {
        self.code = code
        self.message = message
        self.retry_after_ms = retry_after_ms
    }
}
