#!/usr/bin/env bash
# check_openapi_banner.sh — verifies that swift-openapi-generator output files
# carry the expected AUTOGENERATED banner with the correct generator version.
#
# Usage:
#   ./scripts/check_openapi_banner.sh
#
# Exits non-zero if any checked file is missing the banner or reports a
# different generator version than the pinned SWIFT_OPENAPI_VERSION below.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

SWIFT_OPENAPI_VERSION="1.6.0"

# Files produced by the swift-openapi-generator command plugin.
# These live in Sources/Octomil/ (same directory as openapi.yaml).
GENERATED_FILES=(
    "$REPO_ROOT/Sources/Octomil/Types.swift"
    "$REPO_ROOT/Sources/Octomil/Client.swift"
)

FAIL=0

for f in "${GENERATED_FILES[@]}"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: expected generated file not found: $f" >&2
        FAIL=1
        continue
    fi

    if ! head -5 "$f" | grep -q "AUTOGENERATED"; then
        echo "ERROR: AUTOGENERATED banner missing in $f" >&2
        FAIL=1
        continue
    fi

    if ! head -5 "$f" | grep -q "swift-openapi-generator==${SWIFT_OPENAPI_VERSION}"; then
        echo "ERROR: generator version mismatch in $f" >&2
        echo "  Expected: swift-openapi-generator==${SWIFT_OPENAPI_VERSION}" >&2
        echo "  Found:    $(head -5 "$f" | grep -o 'swift-openapi-generator==[^ ]*' || echo '(not found)')" >&2
        FAIL=1
        continue
    fi

    echo "  OK: $f (swift-openapi-generator==${SWIFT_OPENAPI_VERSION})"
done

if [ "$FAIL" -ne 0 ]; then
    echo ""
    echo "Banner check failed. Run 'make openapi-generate' to regenerate." >&2
    exit 1
fi

echo ""
echo "All generated files carry the correct AUTOGENERATED banner."
exit 0
