#!/usr/bin/env bash
# check_openapi_banner.sh — verifies that swift-openapi-generator output files
# carry the expected AUTOGENERATED banner with the correct generator version.
#
# Usage:
#   ./scripts/check_openapi_banner.sh
#
# Exits non-zero if any generated file is missing the banner or reports a
# different generator version than the pinned SWIFT_OPENAPI_VERSION below.
#
# The version pin here MUST stay in lockstep with:
#   - Package.swift (swift-openapi-generator dependency)
#   - octomil-contracts/tools/sdkgen/matrix.yaml (kotlin/swift section)
#   - octomil-contracts/tools/sdkgen/generate-swift.sh (SWIFT_OPENAPI_VERSION)

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

SWIFT_OPENAPI_VERSION="1.12.2"

# Files produced by the swift-openapi-generator command plugin live under
# Sources/Octomil/GeneratedSources/ (Client.swift + Types.swift). The plugin
# emits a variable file set, so scan the directory rather than hard-coding names
# — a stale list silently passes the gate even when the generator's output shape
# changes. NOTE: Sources/Octomil/Generated/ is a DIFFERENT directory holding the
# contract domain enums (codegen/generate.py output, "Auto-generated from
# octomil-contracts" banner) — it is NOT swift-openapi output and is gated by the
# contracts repo, so it is deliberately excluded here.
GENERATED_DIR="$REPO_ROOT/Sources/Octomil/GeneratedSources"

if [ ! -d "$GENERATED_DIR" ]; then
    echo "ERROR: generated directory not found: $GENERATED_DIR" >&2
    echo "  Run 'make openapi-generate' (or the contracts script generate-swift.sh) first." >&2
    exit 1
fi

# Collect .swift files at any depth under Generated/.
# Use a Bash 3.2-compatible read loop (macOS / macos-14 GitHub runners
# ship /bin/bash 3.2.57 which has no `mapfile`).
GENERATED_FILES=()
while IFS= read -r line; do
    GENERATED_FILES+=("$line")
done < <(find "$GENERATED_DIR" -type f -name "*.swift" | sort)

if [ "${#GENERATED_FILES[@]}" -eq 0 ]; then
    echo "ERROR: no .swift files found under $GENERATED_DIR" >&2
    echo "  Run 'make openapi-generate' to populate the directory." >&2
    exit 1
fi

FAIL=0

for f in "${GENERATED_FILES[@]}"; do
    if ! head -5 "$f" | grep -q "AUTOGENERATED"; then
        echo "ERROR: AUTOGENERATED banner missing in $f" >&2
        FAIL=1
        continue
    fi

    if ! head -5 "$f" | grep -q "swift-openapi-generator==${SWIFT_OPENAPI_VERSION}"; then
        echo "ERROR: generator version mismatch in $f" >&2
        echo "  Expected: swift-openapi-generator==${SWIFT_OPENAPI_VERSION}" >&2
        echo "  Found:    $(head -5 "$f" | grep -o 'swift-openapi-generator==[^ ]*' || echo '(not found)')" >&2
        FAIL=1
        continue
    fi

    echo "  OK: ${f#$REPO_ROOT/} (swift-openapi-generator==${SWIFT_OPENAPI_VERSION})"
done

if [ "$FAIL" -ne 0 ]; then
    echo ""
    echo "Banner check failed. Run 'make openapi-generate' to regenerate." >&2
    exit 1
fi

echo ""
echo "All ${#GENERATED_FILES[@]} generated file(s) carry the correct AUTOGENERATED banner."
exit 0
