import Foundation

/// A message in a chat conversation, mirroring the OpenAI Chat Completions API.
///
/// ```swift
/// let messages: [ChatMessage] = [
///     .system("You are a helpful assistant."),
///     .user("What is machine learning?"),
/// ]
/// ```
public struct ChatMessage: Codable, Sendable {
    /// The role of the message author.
    public let role: Role
    /// The text content of the message. Nil when the assistant uses tool calls.
    public let content: String?
    /// An optional name for the participant.
    public let name: String?
    /// Tool calls generated by the model. Only present on assistant messages.
    public let toolCalls: [LegacyToolCall]?
    /// The ID of the tool call this message is a response to.
    public let toolCallId: String?

    public enum Role: String, Codable, Sendable {
        case system
        case user
        case assistant
        case tool
    }

    public init(
        role: Role,
        content: String? = nil,
        name: String? = nil,
        toolCalls: [LegacyToolCall]? = nil,
        toolCallId: String? = nil
    ) {
        self.role = role
        self.content = content
        self.name = name
        self.toolCalls = toolCalls
        self.toolCallId = toolCallId
    }

    // MARK: - Convenience factories

    public static func system(_ content: String) -> ChatMessage {
        ChatMessage(role: .system, content: content)
    }

    public static func user(_ content: String) -> ChatMessage {
        ChatMessage(role: .user, content: content)
    }

    public static func assistant(_ content: String) -> ChatMessage {
        ChatMessage(role: .assistant, content: content)
    }

    public static func tool(_ content: String, toolCallId: String) -> ChatMessage {
        ChatMessage(role: .tool, content: content, toolCallId: toolCallId)
    }

    enum CodingKeys: String, CodingKey {
        case role, content, name
        case toolCalls = "tool_calls"
        case toolCallId = "tool_call_id"
    }
}
