import Foundation

/// A tool the model may call, mirroring the OpenAI tool format.
///
/// ```swift
/// let tool = Tool.function(
///     name: "get_weather",
///     description: "Get the current weather for a location",
///     parameters: ["type": "object", "properties": ["location": ["type": "string"]]]
/// )
/// ```
public struct Tool: Codable, Sendable {
    /// The type of tool. Currently only "function" is supported.
    public let type: String
    /// The function definition.
    public let function: FunctionDef

    public init(type: String = "function", function: FunctionDef) {
        self.type = type
        self.function = function
    }

    public static func function(
        name: String,
        description: String,
        parameters: [String: Any]? = nil
    ) -> Tool {
        let jsonParams: [String: AnyCodable]?
        if let params = parameters {
            jsonParams = params.mapValues { AnyCodable($0) }
        } else {
            jsonParams = nil
        }
        return Tool(
            type: "function",
            function: FunctionDef(name: name, description: description, parameters: jsonParams)
        )
    }
}

/// A function definition within a tool.
public struct FunctionDef: Codable, Sendable {
    public let name: String
    public let description: String
    public let parameters: [String: AnyCodable]?

    public init(name: String, description: String, parameters: [String: AnyCodable]? = nil) {
        self.name = name
        self.description = description
        self.parameters = parameters
    }
}

/// A tool call generated by the model (OpenAI wire format).
public struct LegacyToolCall: Codable, Sendable {
    public let id: String
    public let type: String
    public let function: FunctionCall

    public init(id: String, type: String = "function", function: FunctionCall) {
        self.id = id
        self.type = type
        self.function = function
    }
}

/// A function call with name and serialized arguments.
public struct FunctionCall: Codable, Sendable {
    public let name: String
    public let arguments: String

    public init(name: String, arguments: String) {
        self.name = name
        self.arguments = arguments
    }
}

/// Type-erased Codable wrapper for JSON values.
public struct AnyCodable: Codable, Sendable {
    public let value: Any

    public init(_ value: Any) {
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let str = try? container.decode(String.self) {
            value = str
        } else if let int = try? container.decode(Int.self) {
            value = int
        } else if let double = try? container.decode(Double.self) {
            value = double
        } else if let bool = try? container.decode(Bool.self) {
            value = bool
        } else if let dict = try? container.decode([String: AnyCodable].self) {
            value = dict.mapValues { $0.value }
        } else if let array = try? container.decode([AnyCodable].self) {
            value = array.map { $0.value }
        } else {
            value = NSNull()
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        if let str = value as? String {
            try container.encode(str)
        } else if let int = value as? Int {
            try container.encode(int)
        } else if let double = value as? Double {
            try container.encode(double)
        } else if let bool = value as? Bool {
            try container.encode(bool)
        } else if let dict = value as? [String: Any] {
            try container.encode(dict.mapValues { AnyCodable($0) })
        } else if let array = value as? [Any] {
            try container.encode(array.map { AnyCodable($0) })
        } else {
            try container.encodeNil()
        }
    }
}
